#!/usr/bin/env bun

process.on('SIGUSR1', function() {
  Bun.write(Bun.stderr, 'SIGHUSR1');
  process.exit();
});

process.on('SIGUSR2', function() {
  Bun.write(Bun.stderr, 'SIGUSR2');
  process.exit();
});

process.on('SIGTERM', function() {
  Bun.write(Bun.stderr, 'SIGTERM');
  process.exit();
});

process.on('SIGINT', function() {
  Bun.write(Bun.stderr, 'SIGINT');
  process.exit();
});

process.on('SIGHUP', function() {
  Bun.write(Bun.stderr, 'SIGHUP');
  process.exit();
});

Bun.write(Bun.stderr, 'Listening for signal...');
setInterval(function() {}, 1000); // Stay running
