name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        bun-version: [0.2.0]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun Runtime
      uses: antongolub/action-setup-bun@v1 # or @v1.x.x
      with:
        # Optional, if empty the latest bun version will be used
        # Examples: 0.0.77, 0.1.2, >=0.1, *
        bun-version: ${{ matrix.bun-version }}
    - name: bun install
      run: bun i
    - name: bun upgrade
      run: bun upgrade --canary
    - name: bun wiptest
      run: ls tests/*.test.js | xargs -L 1 bun wiptest
